name: Generate source code diff
on: [pull_request]
jobs:
  diff:
    name: Diff source code
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          # reference the PR's base commit
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Install diffutils
        run: |
          brew install diffutils
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Generate pre-PR sources
        run: |
          ./gradlew decompile --stacktrace
      - name: Rename generated source folder
        run: |
          mv ./namedSrc ./pre-pr-src
      - uses: actions/checkout@v3
        with:
          # reference the PR's head commit
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Double check gradle wrapper post-checkout
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Generate post-PR sources
        run: |
          ./gradlew decompile --stacktrace
      - name: Rename generated source folder
        run: |
          mv ./namedSrc ./post-pr-src
      - name: Diff source code
        run: |
          diff ./pre-pr-src ./post-pr-src > sources.diff
      - name: Upload diff
        uses: actions/upload-artifact@v3
        with:
          path: sources.diff
          name: Decompiled source diff
        