name: Generate source code diff
on: [pull_request]
jobs:
  pre:
    name: Gen pre-commit sources
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          # reference the PR's base commit
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Generate pre-PR sources
        run: |
          ./gradlew decompile --stacktrace
      - name: Rename generated source folder
        run: |
          mv ./namedSrc ./pre-pr-src
      - name: Compress pre-PR sources
        run: |
          zip -r pre-pr-src.zip ./pre-pr-src
      - name: Upload pre-PR sources
        uses: actions/upload-artifact@v3
        with:
          name: pre-pr-src.zip
          path: pre-pr-src.zip
  post:
    name: Gen post-commit sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # reference the PR's head commit
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Generate post-PR sources
        run: |
          ./gradlew decompile --stacktrace
      - name: Rename generated source folder
        run: |
          mv ./namedSrc ./post-pr-src
      - name: Compress post-PR sources
        run: |
          zip -r post-pr-src.zip ./post-pr-src
      - name: Upload post-PR sources
        uses: actions/upload-artifact@v3
        with:
          name: post-pr-src.zip
          path: post-pr-src.zip
  diff:
    name: Generate diff
    runs-on: ubuntu-latest
    needs: [pre, post]
    steps:
      - name: Get pre-PR sources
        uses: actions/download-artifact@v3
        with:
          name: pre-pr-src.zip
          path: ~/pre-pr-src.zip
      - name: Get post-PR sources
        uses: actions/download-artifact@v3
        with:
          name: post-pr-src.zip
          path: ~/post-pr-src.zip
      - name: Decompress sources
        run: |
          unzip pre-pr-src.zip
          unzip post-pr-src.zip
      - name: Diff source code
        run: |
          diff ./pre-pr-src ./post-pr-src > sources.diff
      - name: Upload diff
        uses: actions/upload-artifact@v3
        with:
          path: sources.diff
          name: sources.diff
        