name: Publish
on: [push]
jobs:
  build:
    strategy:
      matrix:
        java: [16-jdk]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - run: ./gradlew publish --stacktrace
